version: '{build}'
skip_tags: true
image:
  - Visual Studio 2017
  - Ubuntu
configuration:
  - Release
build_script:
  - ps: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Serilog.*.nupkg
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - sh build.sh
deploy:
  - provider: NuGet
    api_key:
      secure: hHbvIML/EUrC0+eQvNS0oTd0++/EJHLGUrfvcvY1LBPY4FKRgAOkkq5sWygTNHY7
    skip_symbols: true
    on:
      branch: /^(master|dev)$/
  - provider: GitHub
    auth_token:
      secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
    artifact: /Serilog.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: master
